import type { WorkspaceRouteKey } from '../router/workspace-routes'

// 页面说明紧随外部主标题；卡片专注操作、筛选与业务内容。
export const workspacePageDescriptions: Partial<Record<WorkspaceRouteKey, string>> = {
  otherInbounds: '登记期初、赠品等非采购来源入库，确认后增加库存。',
  warehouseOutbounds: '查看其他用途出库与采购退货，确认后扣减库存。',
  stock: '按仓库查看物料当前库存，数量随已确认的出入库单据更新。',
  inventoryLedger: '按仓库和物料核对期初、每笔变动及期末。选择来源后显示该来源范围内的累计数量。',
  transfers: '在仓库之间调拨物料，确认后同时更新来源仓库与目标仓库的库存。',
  stockAdjustments: '调整量可正可负；建单人不能审批自己的单据。审批通过后由仓库确认才记库存流水。',
  stocktakes: '核对账面与实盘数量，确认差异后更新库存；库存变化时需重新盘点。',
  inventoryReports: '按仓库、物料和日期查询库存报表，支持导出当前结果。',
  sales: '查看客户订单、交付进度与销售明细，确认后按单办理出库。',
  salesReturns: '按原出库明细办理客户退货，确认后更新库存与应收来源。',
  shipments: '按销售订单分批出库，确认后扣减库存并记录应收来源。',
  warehouses: '默认主仓库以及已被业务单据引用的仓库不能删除。',
  catalog: '请按规格建立独立物料编码，同一规格无需为不同供应商重复建档。',
  customers: '集中查询和新增客户资料，销售订单使用同一份客户名单。',
  suppliers: '选择“供货物料”管理供应商与现有物料的绑定。',
  roles: '新增职务后可按模块、单据和操作分别授权；内置职务仅供查看。',
  materialIssues: '按工单剩余需料分批领料，确认后更新源仓库存。',
  materialReturns: '按原领料单退回物料，确认后更新库存与工单净领料数量。',
  productionCompletions: '记录报工、质检与合格品入库，保留取消及冲销记录。',
  boms: '维护成品配方与版本，同一成品只允许一个启用版本。',
  workOrders: '查看工单需料与报工进度，下达后办理领料和完工。',
  purchase: '查看采购明细、入库进度与订单状态。确认订单后按采购流程收货入库。',
  receipts: '采购收货生成待入库单，仓库确认后增加库存；错误记录可填写原因冲销。',
  purchaseReturns: '按原入库明细办理退货，提交后由仓库确认出库。',
  purchaseRequests: '登记采购需求，审批通过后可按剩余数量分批生成采购订单。',
  goodsReceipts: '按采购订单登记实收与拒收数量，确认合格数量后生成待入库单。',
  purchaseReports: '按供应商、物料和日期查询采购报表，表格与 CSV 使用同一份服务端筛选结果。',
  inventoryValuation: '按公司范围的物料移动加权平均计算；缺少价格来源时金额显示待核价。',
  finance: '按订单核对业务净额、收付款净额与未结金额。',
  financePayments: '登记收款、付款与退款；录错时冲销更正，保留原始记录。',
  financeSources: '查看已确认出入库和退货产生的金额来源，追溯单据、物料与操作人。',
  productionCosts: '材料单价按凭据人工核定，金额按已领减已退数量计算。存在待核价领料时，总成本显示待核价；这不是库存计价或总账凭证。',
  users: '管理用户、角色分配和账号状态，支持为其他用户重置密码。',
  permissionCatalog: '名称用于页面展示；内部代码用于服务端授权，不能修改。',
  settings: '查看当前连接、修改账号密码并管理本机服务。',
}
